# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MIvXKo0dU4LUAcUnSoZe_KTAmyShPo3a
"""

!pip install torch torchvision matplotlib tqdm

import torch
import torch.nn as nn
import torch.optim as optim
import torchvision.transforms as transforms
import matplotlib.pyplot as plt
from tqdm import tqdm
import numpy as np
import random

from torchvision.datasets import CIFAR10
from torchvision.models import resnet18
from torch.utils.data import DataLoader, Subset

# =====================
# Seeding (UNCHANGED)
# =====================
def seed_everything(seed=42):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)

    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False

seed_everything(42)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Device:", device)

def seed_worker(worker_id):
    worker_seed = torch.initial_seed() % 2**32
    np.random.seed(worker_seed)
    random.seed(worker_seed)

g = torch.Generator()
g.manual_seed(42)

# =====================
# Transforms
# =====================
transform_aug = transforms.Compose([
    transforms.RandomCrop(32, padding=4),
    transforms.RandomHorizontalFlip(),
    transforms.ToTensor()
])

transform_no_aug = transforms.Compose([
    transforms.ToTensor()
])

# =====================
# Dataset
# =====================
train_aug_dataset = CIFAR10(root='./data', train=True, download=True, transform=transform_aug)
train_noaug_dataset = CIFAR10(root='./data', train=True, download=True, transform=transform_no_aug)

val_dataset = CIFAR10(root='./data', train=False, download=True, transform=transform_no_aug)

# Subset (same idea as before)
# subset_ratio = 0.1
subset_size = int(len(train_noaug_dataset)) # *subset ratio

indices = np.random.choice(len(train_noaug_dataset), subset_size, replace=False)

train_aug_subset = Subset(train_aug_dataset, indices)
train_noaug_subset = Subset(train_noaug_dataset, indices)

trainloader_aug = DataLoader(train_aug_subset, batch_size=128, shuffle=True,
                             num_workers=2, worker_init_fn=seed_worker, generator=g)

trainloader_noaug = DataLoader(train_noaug_subset, batch_size=128, shuffle=True,
                               num_workers=2, worker_init_fn=seed_worker, generator=g)

valloader = DataLoader(val_dataset, batch_size=128, shuffle=False,
                       num_workers=2, worker_init_fn=seed_worker, generator=g)

print("Training samples:", subset_size)

# =====================
# Model (ResNet18 + optional dropout)
# =====================
class ResNetWithDropout(nn.Module):
    def __init__(self, use_dropout=True):
        super().__init__()
        self.model = resnet18(weights=None)
        self.use_dropout = use_dropout
        self.dropout = nn.Dropout(p=0.5)

        self.model.fc = nn.Linear(self.model.fc.in_features, 10)

    def forward(self, x):
        x = self.model.conv1(x)
        x = self.model.bn1(x)
        x = self.model.relu(x)
        x = self.model.maxpool(x)

        x = self.model.layer1(x)
        x = self.model.layer2(x)
        x = self.model.layer3(x)
        x = self.model.layer4(x)

        x = self.model.avgpool(x)
        x = torch.flatten(x, 1)

        if self.use_dropout:
            x = self.dropout(x)

        x = self.model.fc(x)
        return x

def create_model(use_dropout=True):
    return ResNetWithDropout(use_dropout).to(device)

# =====================
# Accuracy
# =====================
def accuracy(model, loader):
    model.eval()
    correct = 0
    total = 0

    with torch.no_grad():
        for x,y in loader:
            x = x.to(device)
            y = y.to(device)

            out = model(x)
            _,pred = torch.max(out,1)

            correct += (pred==y).sum().item()
            total += y.size(0)

    return correct/total

# =====================
# Training loop
# =====================
def run_experiment(loader, weight_decay, dropout, max_steps=1500):

    model = create_model(dropout)

    optimizer = optim.SGD(
        model.parameters(),
        lr=0.1,   # higher LR works better for ResNet
        momentum=0.9,
        weight_decay=weight_decay
    )

    criterion = nn.CrossEntropyLoss()

    steps, train_acc, val_acc = [], [], []
    step = 0

    while step < max_steps:
        for x,y in loader:
            model.train()

            x = x.to(device)
            y = y.to(device)

            optimizer.zero_grad()
            out = model(x)
            loss = criterion(out,y)

            loss.backward()
            optimizer.step()

            if step % 100 == 0:
                tr = accuracy(model, loader)
                val = accuracy(model, valloader)

                print("Step:",step,"Train:",tr,"Val:",val)

                steps.append(step)
                train_acc.append(tr)
                val_acc.append(val)

            step += 1
            if step >= max_steps:
                break

    return steps, train_acc, val_acc

# =====================
# Experiments
# =====================
print("Experiment 1: augmentation + wd + dropout")
s1,tr1,val1 = run_experiment(trainloader_aug,1e-4,True)

print("Experiment 2: wd only")
s2,tr2,val2 = run_experiment(trainloader_noaug,1e-4,False)

print("Experiment 3: no regularization")
s3,tr3,val3 = run_experiment(trainloader_noaug,0,False)

# =====================
# Plot
# =====================
plt.figure(figsize=(8,6))

plt.plot(s1,val1,'o-',label='test(w aug, wd, dropout)')
plt.plot(s1,tr1,'o-',label='train(w aug, wd, dropout)')

plt.plot(s2,val2,'D-',label='test(w/o aug, wd)')
plt.plot(s2,tr2,'D-',label='train(w/o aug, wd)')

plt.plot(s3,val3,'-',label='test(w/o aug, wd, dropout)')
plt.plot(s3,tr3,'-',label='train(w/o aug, wd, dropout)')

plt.xlabel("training steps")
plt.ylabel("accuracy")

plt.legend()
plt.grid()
plt.show()