# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12Xxg7wymLVdcBuZ5Ud8j1pOJXFJ--pnn
"""

!pip install torch torchvision matplotlib tqdm

import torch
import torch.nn as nn
import torch.optim as optim
import torchvision.transforms as transforms
import matplotlib.pyplot as plt
from tqdm import tqdm
import os

from torchvision.datasets import ImageFolder
from torchvision.models import inception_v3
from torch.utils.data import DataLoader, Subset
import numpy as np
import random

def seed_everything(seed=42):

    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)

    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Device:", device)

def seed_worker(worker_id):

    worker_seed = torch.initial_seed() % 2**32
    np.random.seed(worker_seed)
    random.seed(worker_seed)
g = torch.Generator()
g.manual_seed(42)


if not os.path.exists("tiny-imagenet-200"):
    !wget http://cs231n.stanford.edu/tiny-imagenet-200.zip
    !unzip -q tiny-imagenet-200.zip


import shutil

val_dir = "tiny-imagenet-200/val"
img_dir = os.path.join(val_dir, "images")

if os.path.exists(img_dir):
    with open(os.path.join(val_dir, "val_annotations.txt")) as f:
        data = f.readlines()

    for line in data:
        words = line.split("\t")
        img, label = words[0], words[1]

        label_dir = os.path.join(val_dir, label)
        os.makedirs(label_dir, exist_ok=True)

        src = os.path.join(img_dir, img)
        dst = os.path.join(label_dir, img)

        if os.path.exists(src):
            shutil.move(src, dst)

    os.rmdir(img_dir)



transform_aug = transforms.Compose([
    transforms.Resize(320),
    transforms.RandomResizedCrop(299),
    transforms.RandomHorizontalFlip(),
    transforms.ToTensor()
])

transform_no_aug = transforms.Compose([
    transforms.Resize((299,299)),
    transforms.ToTensor()
])



train_aug_dataset = ImageFolder(
    "tiny-imagenet-200/train",
    transform=transform_aug
)

train_noaug_dataset = ImageFolder(
    "tiny-imagenet-200/train",
    transform=transform_no_aug
)

val_dataset = ImageFolder(
    "tiny-imagenet-200/val",
    transform=transform_no_aug
)


subset_ratio = 0.1
subset_size = int(len(train_noaug_dataset) * subset_ratio)

indices = np.random.choice(len(train_noaug_dataset), subset_size, replace=False)

train_aug_subset = Subset(train_aug_dataset, indices)
train_noaug_subset = Subset(train_noaug_dataset, indices)

trainloader_aug = DataLoader(
    train_aug_subset,
    batch_size=64,
    shuffle=True,
    num_workers=2,
    worker_init_fn=seed_worker,
    generator=g
)

trainloader_noaug = DataLoader(
    train_noaug_subset,
    batch_size=64,
    shuffle=True,
    num_workers=2,
    worker_init_fn=seed_worker,
    generator=g
)

valloader = DataLoader(
    val_dataset,
    batch_size=64,
    shuffle=False,
    num_workers=2,
    worker_init_fn=seed_worker,
    generator=g
)

print("Training samples:", subset_size)


def create_model(use_dropout=True):

    model = inception_v3(weights=None, aux_logits=False)

    if not use_dropout:
        model.dropout = nn.Identity()

    model.fc = nn.Linear(model.fc.in_features, 200)

    return model.to(device)



def accuracy(model, loader):

    model.eval()
    correct = 0
    total = 0

    with torch.no_grad():
        for x,y in loader:

            x = x.to(device)
            y = y.to(device)

            out = model(x)
            _,pred = torch.max(out,1)

            correct += (pred==y).sum().item()
            total += y.size(0)

    return correct/total



def run_experiment(loader, weight_decay, dropout, max_steps=1500):

    model = create_model(dropout)

    optimizer = optim.SGD(
        model.parameters(),
        lr=0.01,
        momentum=0.9,
        weight_decay=weight_decay
    )

    criterion = nn.CrossEntropyLoss()

    steps = []
    train_acc = []
    val_acc = []

    step = 0

    while step < max_steps:

        for x,y in loader:

            model.train()

            x = x.to(device)
            y = y.to(device)

            optimizer.zero_grad()

            out = model(x)
            loss = criterion(out,y)

            loss.backward()
            optimizer.step()

            if step % 100 == 0:

                tr = accuracy(model, loader)
                val = accuracy(model, valloader)

                print("Step:",step,"Train:",tr,"Val:",val)

                steps.append(step)
                train_acc.append(tr)
                val_acc.append(val)

            step += 1

            if step >= max_steps:
                break

    return steps, train_acc, val_acc



print("Experiment 1: augmentation + wd + dropout")
s1,tr1,val1 = run_experiment(trainloader_aug,1e-4,True)

print("Experiment 2: wd only")
s2,tr2,val2 = run_experiment(trainloader_noaug,1e-4,False)

print("Experiment 3: no regularization")
s3,tr3,val3 = run_experiment(trainloader_noaug,0,False)



plt.figure(figsize=(8,6))

plt.plot(s1,val1,'o-',label='test(w aug, wd, dropout)')
plt.plot(s1,tr1,'o-',label='train(w aug, wd, dropout)')

plt.plot(s2,val2,'D-',label='test(w/o aug, wd)')
plt.plot(s2,tr2,'D-',label='train(w/o aug, wd)')

plt.plot(s3,val3,'-',label='test(w/o aug, wd, dropout)')
plt.plot(s3,tr3,'-',label='train(w/o aug, wd, dropout)')

plt.xlabel("training steps")
plt.ylabel("accuracy")

plt.legend()
plt.grid()

plt.show()