# -*- coding: utf-8 -*-
"""Overparametrized_models.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1C8zVpAWIY5RvexbdmE5IC2Gdo0GnZdG7
"""

!pip install torch torchvision matplotlib tqdm

import torch
import torch.nn as nn
import torch.optim as optim
import torchvision.transforms as transforms
import matplotlib.pyplot as plt
from tqdm import tqdm
import os

from torchvision.datasets import ImageFolder
from torchvision.models import inception_v3
from torch.utils.data import DataLoader, Subset
import numpy as np
import random

def seed_everything(seed=42):

    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)

    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Device:", device)

def seed_worker(worker_id):

    worker_seed = torch.initial_seed() % 2**32
    np.random.seed(worker_seed)
    random.seed(worker_seed)
g = torch.Generator()
g.manual_seed(42)


if not os.path.exists("tiny-imagenet-200"):
    !wget http://cs231n.stanford.edu/tiny-imagenet-200.zip
    !unzip -q tiny-imagenet-200.zip


import shutil

val_dir = "tiny-imagenet-200/val"
img_dir = os.path.join(val_dir, "images")

if os.path.exists(img_dir):
    with open(os.path.join(val_dir, "val_annotations.txt")) as f:
        data = f.readlines()

    for line in data:
        words = line.split("\t")
        img, label = words[0], words[1]

        label_dir = os.path.join(val_dir, label)
        os.makedirs(label_dir, exist_ok=True)

        src = os.path.join(img_dir, img)
        dst = os.path.join(label_dir, img)

        if os.path.exists(src):
            shutil.move(src, dst)

    os.rmdir(img_dir)



transform_aug = transforms.Compose([
    transforms.Resize(320),
    transforms.RandomResizedCrop(299),
    transforms.RandomHorizontalFlip(),
    transforms.ToTensor()
])

transform_no_aug = transforms.Compose([
    transforms.Resize((299,299)),
    transforms.ToTensor()
])



train_aug_dataset = ImageFolder(
    "tiny-imagenet-200/train",
    transform=transform_aug
)

train_noaug_dataset = ImageFolder(
    "tiny-imagenet-200/train",
    transform=transform_no_aug
)

val_dataset = ImageFolder(
    "tiny-imagenet-200/val",
    transform=transform_no_aug
)


subset_ratio = 0.1
subset_size = int(len(train_noaug_dataset) * subset_ratio)

indices = np.random.choice(len(train_noaug_dataset), subset_size, replace=False)

train_aug_subset = Subset(train_aug_dataset, indices)
train_noaug_subset = Subset(train_noaug_dataset, indices)

trainloader_aug = DataLoader(
    train_aug_subset,
    batch_size=64,
    shuffle=True,
    num_workers=2,
    worker_init_fn=seed_worker,
    generator=g
)

trainloader_noaug = DataLoader(
    train_noaug_subset,
    batch_size=64,
    shuffle=True,
    num_workers=2,
    worker_init_fn=seed_worker,
    generator=g
)

valloader = DataLoader(
    val_dataset,
    batch_size=64,
    shuffle=False,
    num_workers=2,
    worker_init_fn=seed_worker,
    generator=g
)

print("Training samples:", subset_size)


def create_model(use_dropout=True):

    model = inception_v3(weights=None, aux_logits=False)

    if not use_dropout:
        model.dropout = nn.Identity()

    model.fc = nn.Linear(model.fc.in_features, 200)

    return model.to(device)



def accuracy(model, loader):

    model.eval()
    correct = 0
    total = 0

    with torch.no_grad():
        for x,y in loader:

            x = x.to(device)
            y = y.to(device)

            out = model(x)
            _,pred = torch.max(out,1)

            correct += (pred==y).sum().item()
            total += y.size(0)

    return correct/total



def run_experiment(loader, weight_decay, dropout, max_steps=1500):

    model = create_model(dropout)

    optimizer = optim.SGD(
        model.parameters(),
        lr=0.01,
        momentum=0.9,
        weight_decay=weight_decay
    )

    criterion = nn.CrossEntropyLoss()

    steps = []
    train_acc = []
    val_acc = []

    step = 0

    while step < max_steps:

        for x,y in loader:

            model.train()

            x = x.to(device)
            y = y.to(device)

            optimizer.zero_grad()

            out = model(x)
            loss = criterion(out,y)

            loss.backward()
            optimizer.step()

            if step % 100 == 0:

                tr = accuracy(model, loader)
                val = accuracy(model, valloader)

                print("Step:",step,"Train:",tr,"Val:",val)

                steps.append(step)
                train_acc.append(tr)
                val_acc.append(val)

            step += 1

            if step >= max_steps:
                break

    return steps, train_acc, val_acc



print("Experiment 1: augmentation + wd + dropout")
s1,tr1,val1 = run_experiment(trainloader_aug,1e-4,True)

print("Experiment 2: wd only")
s2,tr2,val2 = run_experiment(trainloader_noaug,1e-4,False)

print("Experiment 3: no regularization")
s3,tr3,val3 = run_experiment(trainloader_noaug,0,False)



plt.figure(figsize=(8,6))

plt.plot(s1,val1,'o-',label='test(w aug, wd, dropout)')
plt.plot(s1,tr1,'o-',label='train(w aug, wd, dropout)')

plt.plot(s2,val2,'D-',label='test(w/o aug, wd)')
plt.plot(s2,tr2,'D-',label='train(w/o aug, wd)')

plt.plot(s3,val3,'-',label='test(w/o aug, wd, dropout)')
plt.plot(s3,tr3,'-',label='train(w/o aug, wd, dropout)')

plt.xlabel("training steps")
plt.ylabel("accuracy")

plt.legend()
plt.grid()

plt.show()

!pip install torch torchvision matplotlib tqdm

import torch
import torch.nn as nn
import torch.optim as optim
import torchvision.transforms as transforms
import matplotlib.pyplot as plt
from tqdm import tqdm
import numpy as np
import random

from torchvision.datasets import CIFAR10
from torchvision.models import resnet18
from torch.utils.data import DataLoader, Subset

# =====================
# Seeding (UNCHANGED)
# =====================
def seed_everything(seed=42):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)

    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False

seed_everything(42)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Device:", device)

def seed_worker(worker_id):
    worker_seed = torch.initial_seed() % 2**32
    np.random.seed(worker_seed)
    random.seed(worker_seed)

g = torch.Generator()
g.manual_seed(42)

# =====================
# Transforms
# =====================
transform_aug = transforms.Compose([
    transforms.RandomCrop(32, padding=4),
    transforms.RandomHorizontalFlip(),
    transforms.ToTensor()
])

transform_no_aug = transforms.Compose([
    transforms.ToTensor()
])

# =====================
# Dataset
# =====================
train_aug_dataset = CIFAR10(root='./data', train=True, download=True, transform=transform_aug)
train_noaug_dataset = CIFAR10(root='./data', train=True, download=True, transform=transform_no_aug)

val_dataset = CIFAR10(root='./data', train=False, download=True, transform=transform_no_aug)

# Subset (same idea as before)
# subset_ratio = 0.1
subset_size = int(len(train_noaug_dataset)) # *subset ratio

indices = np.random.choice(len(train_noaug_dataset), subset_size, replace=False)

train_aug_subset = Subset(train_aug_dataset, indices)
train_noaug_subset = Subset(train_noaug_dataset, indices)

trainloader_aug = DataLoader(train_aug_subset, batch_size=128, shuffle=True,
                             num_workers=2, worker_init_fn=seed_worker, generator=g)

trainloader_noaug = DataLoader(train_noaug_subset, batch_size=128, shuffle=True,
                               num_workers=2, worker_init_fn=seed_worker, generator=g)

valloader = DataLoader(val_dataset, batch_size=128, shuffle=False,
                       num_workers=2, worker_init_fn=seed_worker, generator=g)

print("Training samples:", subset_size)

# =====================
# Model (ResNet18 + optional dropout)
# =====================
class ResNetWithDropout(nn.Module):
    def __init__(self, use_dropout=True):
        super().__init__()
        self.model = resnet18(weights=None)
        self.use_dropout = use_dropout
        self.dropout = nn.Dropout(p=0.5)

        self.model.fc = nn.Linear(self.model.fc.in_features, 10)

    def forward(self, x):
        x = self.model.conv1(x)
        x = self.model.bn1(x)
        x = self.model.relu(x)
        x = self.model.maxpool(x)

        x = self.model.layer1(x)
        x = self.model.layer2(x)
        x = self.model.layer3(x)
        x = self.model.layer4(x)

        x = self.model.avgpool(x)
        x = torch.flatten(x, 1)

        if self.use_dropout:
            x = self.dropout(x)

        x = self.model.fc(x)
        return x

def create_model(use_dropout=True):
    return ResNetWithDropout(use_dropout).to(device)

# =====================
# Accuracy
# =====================
def accuracy(model, loader):
    model.eval()
    correct = 0
    total = 0

    with torch.no_grad():
        for x,y in loader:
            x = x.to(device)
            y = y.to(device)

            out = model(x)
            _,pred = torch.max(out,1)

            correct += (pred==y).sum().item()
            total += y.size(0)

    return correct/total

# =====================
# Training loop
# =====================
def run_experiment(loader, weight_decay, dropout, max_steps=1500):

    model = create_model(dropout)

    optimizer = optim.SGD(
        model.parameters(),
        lr=0.1,   # higher LR works better for ResNet
        momentum=0.9,
        weight_decay=weight_decay
    )

    criterion = nn.CrossEntropyLoss()

    steps, train_acc, val_acc = [], [], []
    step = 0

    while step < max_steps:
        for x,y in loader:
            model.train()

            x = x.to(device)
            y = y.to(device)

            optimizer.zero_grad()
            out = model(x)
            loss = criterion(out,y)

            loss.backward()
            optimizer.step()

            if step % 100 == 0:
                tr = accuracy(model, loader)
                val = accuracy(model, valloader)

                print("Step:",step,"Train:",tr,"Val:",val)

                steps.append(step)
                train_acc.append(tr)
                val_acc.append(val)

            step += 1
            if step >= max_steps:
                break

    return steps, train_acc, val_acc

# =====================
# Experiments
# =====================
print("Experiment 1: augmentation + wd + dropout")
s1,tr1,val1 = run_experiment(trainloader_aug,1e-4,True)

print("Experiment 2: wd only")
s2,tr2,val2 = run_experiment(trainloader_noaug,1e-4,False)

print("Experiment 3: no regularization")
s3,tr3,val3 = run_experiment(trainloader_noaug,0,False)

# =====================
# Plot
# =====================
plt.figure(figsize=(8,6))

plt.plot(s1,val1,'o-',label='test(w aug, wd, dropout)')
plt.plot(s1,tr1,'o-',label='train(w aug, wd, dropout)')

plt.plot(s2,val2,'D-',label='test(w/o aug, wd)')
plt.plot(s2,tr2,'D-',label='train(w/o aug, wd)')

plt.plot(s3,val3,'-',label='test(w/o aug, wd, dropout)')
plt.plot(s3,tr3,'-',label='train(w/o aug, wd, dropout)')

plt.xlabel("training steps")
plt.ylabel("accuracy")

plt.legend()
plt.grid()
plt.show()

import torch
import torch.nn as nn
import torch.optim as optim
import torchvision
import torchvision.transforms as transforms
import matplotlib.pyplot as plt
import numpy as np

# ======================
# Setup
# ======================
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
torch.manual_seed(0)

activations = ["relu", "tanh", "sigmoid", "gelu"]
depths = [2, 4, 6]
epochs = 20
batch_size = 128

# ======================
# Data
# ======================
transform = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize((0.5, 0.5, 0.5),
                         (0.5, 0.5, 0.5))
])

full_trainset = torchvision.datasets.CIFAR10(
    root='./data', train=True, download=True, transform=transform
)

train_size = int(0.8 * len(full_trainset))
val_size = len(full_trainset) - train_size
trainset, valset = torch.utils.data.random_split(full_trainset, [train_size, val_size])

trainloader = torch.utils.data.DataLoader(trainset, batch_size=batch_size, shuffle=True)
valloader = torch.utils.data.DataLoader(valset, batch_size=batch_size, shuffle=False)

testset = torchvision.datasets.CIFAR10(
    root='./data', train=False, download=True, transform=transform
)
testloader = torch.utils.data.DataLoader(testset, batch_size=batch_size, shuffle=False)

# ======================
# Activation
# ======================
def get_activation(name):
    return {
        "relu": nn.ReLU(),
        "tanh": nn.Tanh(),
        "sigmoid": nn.Sigmoid(),
        "gelu": nn.GELU()
    }[name]

# ======================
# CNN Model
# ======================
class CNN(nn.Module):
    def __init__(self, depth, activation):
        super().__init__()

        act = get_activation(activation)
        layers = []

        in_channels = 3
        channels = 32

        # Convolutional blocks
        for i in range(depth): # i is 0-indexed block number
            layers.append(nn.Conv2d(in_channels, channels, kernel_size=3, padding=1))

            # Calculate spatial dimension after previous pooling and current conv
            # Assuming 32x32 initial input. Each MaxPool2d halves the dimension.
            # So, after `i` MaxPool2d operations (from previous blocks), the current spatial dim is 32 / (2**i).
            current_spatial_dim = 32 // (2**i)

            # Only add BatchNorm2d if spatial dimensions are not 1x1
            if current_spatial_dim > 1:
                layers.append(nn.BatchNorm2d(channels))
            else:
                # If spatial dimension is 1x1, use nn.Identity() instead of BatchNorm2d
                layers.append(nn.Identity()) # Placeholder, effectively no-op

            layers.append(act)

            # Apply MaxPool2d only if current_spatial_dim is greater than 1
            if current_spatial_dim > 1:
                layers.append(nn.MaxPool2d(2))
            else:
                # If spatial dimension is 1x1, use nn.Identity() instead of MaxPool2d
                layers.append(nn.Identity()) # Placeholder for MaxPool2d

            in_channels = channels
            channels *= 2

        self.conv = nn.Sequential(*layers)

        # Compute flattened size dynamically
        with torch.no_grad():
            dummy = torch.zeros(1, 3, 32, 32)
            out = self.conv(dummy)
            self.flat_dim = out.view(1, -1).shape[1]

        self.fc = nn.Linear(self.flat_dim, 10)

    def forward(self, x):
        x = self.conv(x)
        x = x.view(x.size(0), -1)
        return self.fc(x)

# ======================
# Train Function
# ======================
def train(model, loader, optimizer, criterion):
    model.train()
    correct, total = 0, 0

    for x, y in loader:
        x, y = x.to(device), y.to(device)

        optimizer.zero_grad()
        out = model(x)
        loss = criterion(out, y)
        loss.backward()
        optimizer.step()

        pred = out.argmax(dim=1)
        correct += (pred == y).sum().item()
        total += y.size(0)

    return correct / total

# ======================
# Evaluation + Margins
# ======================
def evaluate(model, loader):
    model.eval()
    correct, total = 0, 0
    margins = []

    with torch.no_grad():
        for x, y in loader:
            x, y = x.to(device), y.to(device)
            out = model(x)

            pred = out.argmax(dim=1)
            correct += (pred == y).sum().item()
            total += y.size(0)

            # Vectorized margin computation
            correct_scores = out[torch.arange(len(y)), y]

            temp = out.clone()
            temp[torch.arange(len(y)), y] = -1e9
            second_best = temp.max(dim=1).values

            batch_margins = (correct_scores - second_best).cpu().numpy()
            margins.extend(batch_margins)

    return correct / total, margins

# ======================
# Experiment Loop
# ======================
results = {}

for depth in depths:
    for act in activations:
        print(f"\n=== Depth={depth}, Activation={act} ===")

        model = CNN(depth, act).to(device)
        optimizer = optim.Adam(model.parameters(), lr=0.001)
        criterion = nn.CrossEntropyLoss()

        train_hist, val_hist = [], []

        for ep in range(epochs):
            train_acc = train(model, trainloader, optimizer, criterion)
            val_acc, _ = evaluate(model, valloader)

            train_hist.append(train_acc)
            val_hist.append(val_acc)

            print(f"Epoch {ep+1}: Train={train_acc:.4f}, Val={val_acc:.4f}")

        test_acc, test_margins = evaluate(model, testloader)
        train_acc_final, train_margins = evaluate(model, trainloader)

        gap = train_acc_final - test_acc

        results[(act, depth)] = {
            "train_hist": train_hist,
            "val_hist": val_hist,
            "test_acc": test_acc,
            "gap": gap,
            "train_margins": train_margins,
            "test_margins": test_margins
        }

# ======================
# PLOTS
# ======================

# Accuracy curves
for depth in depths:
    plt.figure()
    for act in activations:
        plt.plot(results[(act, depth)]["train_hist"], '--', label=f"{act}-train")
        plt.plot(results[(act, depth)]["val_hist"], '-', label=f"{act}-val")

    plt.title(f"Accuracy | Depth={depth}")
    plt.xlabel("Epoch")
    plt.ylabel("Accuracy")
    plt.legend()
    plt.show()

# Test accuracy comparison
for depth in depths:
    plt.figure()
    accs = [results[(act, depth)]["test_acc"] for act in activations]
    plt.bar(activations, accs)

    plt.title(f"Test Accuracy | Depth={depth}")
    plt.ylabel("Accuracy")
    plt.show()

# Generalization gap
for depth in depths:
    plt.figure()
    gaps = [results[(act, depth)]["gap"] for act in activations]
    plt.bar(activations, gaps)

    plt.title(f"Generalization Gap | Depth={depth}")
    plt.ylabel("Gap")
    plt.show()

# Margin distributions (TEST)
for depth in depths:
    plt.figure()
    for act in activations:
        margins = results[(act, depth)]["test_margins"]
        plt.hist(margins, bins=50, alpha=0.4, label=act)

    plt.title(f"Test Margin Distribution | Depth={depth}")
    plt.legend()
    plt.show()

# Mean margin comparison
for depth in depths:
    plt.figure()

    means = [
        np.mean(results[(act, depth)]["test_margins"])
        for act in activations
    ]

    plt.bar(activations, means)
    plt.title(f"Mean Margin | Depth={depth}")
    plt.ylabel("Margin")
    plt.show()