# -*- coding: utf-8 -*-
"""overpara_problem4_regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_rgRqOEDTPXMKASayJhlUOCzIbslems2
"""

import numpy as np
import matplotlib.pyplot as plt

# ----------------------------
# Setup
# ----------------------------
n      = 200        # number of observations
sigma  = 1.0        # noise std
norm2  = 4.0        # ||theta*||^2 (fixed so theory matches cleanly)
n_runs = 10         # average over multiple draws to reduce noise near d=n

d_values = list(range(10, 600, 5))
errors   = []

# ----------------------------
# Main Experiment Loop
# ----------------------------
for d in d_values:
    run_errors = []

    for _ in range(n_runs):
        # Fresh self-consistent problem for this d
        theta_star = np.random.randn(d)
        theta_star = theta_star / np.linalg.norm(theta_star) * np.sqrt(norm2)

        X   = np.random.randn(n, d)           # design matrix  (n x d)
        eps = sigma * np.random.randn(n)       # noise
        y   = X @ theta_star + eps

        # Minimum-norm estimator (textbook section 12.1.1)
        if d <= n - 2:                         # underparameterized: OLS
            theta_hat = np.linalg.solve(X.T @ X, X.T @ y)
        else:                                  # overparameterized: min-norm via kernel trick
            K = X @ X.T                        # (n x n) kernel matrix
            theta_hat = X.T @ np.linalg.solve(K, y)

        # Excess risk R(theta_hat) = ||theta_hat - theta*||^2  (since Sigma = I)
        run_errors.append(np.sum((theta_hat - theta_star) ** 2))

    errors.append(np.mean(run_errors))

# ----------------------------
# Theoretical Curves
# Eq (12.17): d <= n-2  =>  sigma^2 * d / (n - d - 1)
# Eq (12.18): d >= n+2  =>  sigma^2 * n / (d - n - 1) + ||theta*||^2 * (d - n) / d
# ----------------------------
theory = []
for d in d_values:
    if d <= n - 2:
        val = sigma**2 * d / (n - d - 1)
    elif d >= n + 2:
        val = (sigma**2 * n / (d - n - 1)) + norm2 * (d - n) / d
    else:
        val = np.nan    # blow-up zone around d = n, skip
    theory.append(val)

# ----------------------------
# Plot
# ----------------------------
plt.figure(figsize=(9, 5))

plt.plot(d_values, errors,
         label="Empirical excess risk", color="#378ADD", linewidth=1.8)
plt.plot(d_values, theory,
         label="Theory (eqs 12.17 / 12.18)", color="#D85A30",
         linewidth=1.5, linestyle="--")

plt.axvline(x=n, color="gray", linestyle=":", linewidth=1.2, label=f"d = n = {n}")
plt.ylim(0, min(max(e for e in errors if not np.isnan(e)) * 1.2, 50))
plt.xlabel("Dimension d")
plt.ylabel("Excess risk  E[R(theta_hat)]")
plt.title("Double Descent — Linear Regression with Gaussian Inputs")
plt.legend()
plt.tight_layout()
plt.savefig("double_descent.png", dpi=150)
plt.show()

import numpy as np
import matplotlib.pyplot as plt

# ----------------------------
# Setup
# ----------------------------
n      = 200        # number of training observations
n_test = 2000       # test set size
sigma  = 1.0        # noise std
norm2  = 4.0        # ||theta*||^2
n_runs = 10         # average over multiple draws to reduce noise near d=n

d_values = list(range(10, 600, 5))
test_errors = []

# ----------------------------
# Main Experiment Loop
# ----------------------------
for d in d_values:
    run_errors = []

    for _ in range(n_runs):
        # Fresh self-consistent problem for this d
        theta_star = np.random.randn(d)
        theta_star = theta_star / np.linalg.norm(theta_star) * np.sqrt(norm2)

        # Training data
        X_train = np.random.randn(n, d)
        y_train = X_train @ theta_star + sigma * np.random.randn(n)

        # Minimum-norm estimator
        if d <= n - 2:                          # underparameterized: OLS
            theta_hat = np.linalg.solve(X_train.T @ X_train, X_train.T @ y_train)
        else:                                   # overparameterized: min-norm
            K = X_train @ X_train.T
            theta_hat = X_train.T @ np.linalg.solve(K, y_train)

        # Test error (MSE on fresh test set)
        X_test = np.random.randn(n_test, d)
        y_test = X_test @ theta_star + sigma * np.random.randn(n_test)
        y_pred = X_test @ theta_hat

        mse = np.mean((y_test - y_pred) ** 2)
        run_errors.append(mse)

    test_errors.append(np.mean(run_errors))

# ----------------------------
# Plot
# ----------------------------
plt.figure(figsize=(9, 5))

plt.plot(d_values, test_errors,
         label="Test error (MSE)", color="#378ADD", linewidth=1.8)

plt.axvline(x=n, color="gray", linestyle=":", linewidth=1.2, label=f"d = n = {n}")

# clip y-axis so the spike doesn't squash everything else
finite_errors = [e for e in test_errors if np.isfinite(e)]
plt.ylim(0, min(max(finite_errors) * 1.1, 60))

plt.xlabel("Dimension d")
plt.ylabel("Test Error (MSE)")
plt.title("Double Descent — Test Error, Linear Regression with Gaussian Inputs")
plt.legend()
plt.tight_layout()
plt.savefig("double_descent_test_error.png", dpi=150)
plt.show()

import numpy as np
import matplotlib.pyplot as plt

# ----------------------------
# Setup (matching Figure 12.4)
# ----------------------------
n = 200          # number of observations
d = 400          # ambient dimension (d > n, so overparameterized in X)
sigma2 = 0.25    # noise variance  => optimal risk = sigma2 = 1/4

n_datasets    = 20   # number of dataset draws
n_projections = 20   # number of projection draws per dataset

m_values = list(range(5, 800, 5))   # projection dimension (x-axis)

# ----------------------------
# Covariance matrix Sigma
# Nonisotropic: eigenvalues decay as 1/k so that tr(Sigma) ~ log(d)
# Normalized so that predicting zero => excess risk = theta*^T Sigma theta* = 1
# ----------------------------
eigs = np.array([1.0 / (k + 1) for k in range(d)])   # eigenvalues 1, 1/2, 1/3, ...
Sigma = np.diag(eigs)
Sigma_sqrt = np.diag(np.sqrt(eigs))

# theta* such that theta*^T Sigma theta* = 1  (predicting zero => excess risk = 1)
# Take theta* proportional to ones, then normalize
theta_raw = np.ones(d)
scale = np.sqrt(theta_raw @ Sigma @ theta_raw)
theta_star = theta_raw / scale   # now theta*^T Sigma theta* = 1

# ----------------------------
# Compute min-norm estimator given (X, y, S)
# theta_hat = S eta_hat  where eta_hat = argmin ||y - X S eta||^2
# ----------------------------
def get_theta_hat(X, y, S):
    XS = X @ S                  # n x m
    m = S.shape[1]
    if m <= n - 2:              # underparameterized: OLS
        eta_hat = np.linalg.solve(XS.T @ XS, XS.T @ y)
    else:                       # overparameterized: min-norm
        K = XS @ XS.T          # n x n
        eta_hat = XS.T @ np.linalg.solve(K, y)
    return S @ eta_hat

# ----------------------------
# Excess risk for one (X, eps, S) draw
# R(theta_hat) = (theta_hat - theta*)^T Sigma (theta_hat - theta*)
# ----------------------------
def excess_risk(theta_hat, theta_star, Sigma):
    diff = theta_hat - theta_star
    return diff @ Sigma @ diff

# ----------------------------
# Main experiment
# ----------------------------
all_risks = []   # shape: (len(m_values),)

for m in m_values:
    risks = []

    for _ in range(n_datasets):
        # Draw X with rows from N(0, Sigma)
        Z = np.random.randn(n, d)
        X = Z @ Sigma_sqrt        # rows ~ N(0, Sigma)

        eps = np.sqrt(sigma2) * np.random.randn(n)
        y = X @ theta_star + eps

        for _ in range(n_projections):
            S = np.random.randn(d, m)   # random Gaussian projection

            try:
                theta_hat = get_theta_hat(X, y, S)
                r = excess_risk(theta_hat, theta_star, Sigma)
                if np.isfinite(r):
                    risks.append(r)
            except np.linalg.LinAlgError:
                pass   # skip singular cases near m = n

    all_risks.append(np.mean(risks) if risks else np.nan)

# ----------------------------
# Plot (matching Figure 12.4 style)
# ----------------------------
fig, ax = plt.subplots(figsize=(9, 5))

ax.plot(m_values, all_risks, color="#1D9E75", linewidth=1.8, label="Empirical excess risk")
ax.axvline(x=n, color="gray", linestyle=":", linewidth=1.2, label=f"m = n = {n}")
ax.axhline(y=1.0,    color="#D85A30", linestyle="--", linewidth=1.0, label="Zero-predictor risk = 1")
ax.axhline(y=sigma2, color="#7F77DD", linestyle="--", linewidth=1.0, label=f"Optimal risk = {sigma2}")

# clip y so the spike doesn't squash the rest
finite = [r for r in all_risks if np.isfinite(r)]
ax.set_ylim(0, min(max(finite) * 1.1, 5))
ax.set_xlim(0, max(m_values))

ax.set_xlabel("m  (projection dimension)", fontsize=12)
ax.set_ylabel("Excess risk", fontsize=12)
ax.set_title("Double Descent — Linear Regression with Gaussian Projections\n"
             f"n={n}, d={d}, averaged over {n_datasets} datasets × {n_projections} projections",
             fontsize=11)
ax.legend(fontsize=10)
plt.tight_layout()
plt.savefig("double_descent_projections.png", dpi=150)
plt.show()

import numpy as np
import matplotlib.pyplot as plt

# ----------------------------
# Setup (matching Figure 12.4)
# ----------------------------
n      = 200
d      = 400
sigma2 = 0.25
n_test = 2000

n_datasets    = 5    # increase to 20 for smoother curve (slower)
n_projections = 5    # increase to 20 for smoother curve (slower)

m_values = list(range(5, 800, 15))   # use step=5 for smoother curve (slower)

# ----------------------------
# Nonisotropic covariance, normalized so zero-predictor risk = 1
# ----------------------------
eigs      = np.array([1.0 / (k + 1) for k in range(d)])
Sigma     = np.diag(eigs)
Sigma_sqrt = np.diag(np.sqrt(eigs))

theta_raw  = np.ones(d)
scale      = np.sqrt(theta_raw @ Sigma @ theta_raw)
theta_star = theta_raw / scale    # theta*^T Sigma theta* = 1

# ----------------------------
# Min-norm estimator: theta_hat = S eta_hat
# ----------------------------
def get_theta_hat(X, y, S):
    XS = X @ S
    m  = S.shape[1]
    if m <= n - 2:
        eta_hat = np.linalg.solve(XS.T @ XS, XS.T @ y)
    else:
        K = XS @ XS.T
        eta_hat = XS.T @ np.linalg.solve(K, y)
    return S @ eta_hat

# ----------------------------
# Main experiment
# ----------------------------
all_test_errors = []

for m in m_values:
    errors = []

    for _ in range(n_datasets):
        # Training data  (rows of X ~ N(0, Sigma))
        X_train = np.random.randn(n, d) @ Sigma_sqrt
        eps     = np.sqrt(sigma2) * np.random.randn(n)
        y_train = X_train @ theta_star + eps

        # Test data (fresh, same distribution)
        X_test  = np.random.randn(n_test, d) @ Sigma_sqrt
        eps_test = np.sqrt(sigma2) * np.random.randn(n_test)
        y_test  = X_test @ theta_star + eps_test

        for _ in range(n_projections):
            S = np.random.randn(d, m)

            try:
                theta_hat = get_theta_hat(X_train, y_train, S)
                y_pred    = X_test @ theta_hat
                mse       = np.mean((y_test - y_pred) ** 2)
                if np.isfinite(mse):
                    errors.append(mse)
            except np.linalg.LinAlgError:
                pass

    all_test_errors.append(np.mean(errors) if errors else np.nan)

# ----------------------------
# Plot
# ----------------------------
fig, ax = plt.subplots(figsize=(9, 5))

ax.plot(m_values, all_test_errors,
        color="#1D9E75", linewidth=1.8, label="Test error (MSE)")

ax.axvline(x=n, color="gray", linestyle=":", linewidth=1.2,
           label=f"m = n = {n}")
ax.axhline(y=1.0 + sigma2, color="#D85A30", linestyle="--",
           linewidth=1.0, label=f"Zero-predictor MSE = {1.0 + sigma2}")
ax.axhline(y=sigma2, color="#7F77DD", linestyle="--",
           linewidth=1.0, label=f"Irreducible noise = {sigma2}")

finite = [r for r in all_test_errors if np.isfinite(r)]
ax.set_ylim(0, min(max(finite) * 1.1, 6))
ax.set_xlim(0, max(m_values))

ax.set_xlabel("m  (projection dimension)", fontsize=12)
ax.set_ylabel("Test Error (MSE)", fontsize=12)
ax.set_title(
    "Double Descent — Test Error, Linear Regression with Gaussian Projections\n"
    f"n={n}, d={d}, {n_datasets} datasets × {n_projections} projections",
    fontsize=11)
ax.legend(fontsize=10)
plt.tight_layout()
plt.savefig("double_descent_projections_test_error.png", dpi=150)
plt.show()

