# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MIvXKo0dU4LUAcUnSoZe_KTAmyShPo3a
"""

import torch
import torch.nn as nn
import torch.optim as optim
import torchvision
import torchvision.transforms as transforms
import matplotlib.pyplot as plt
import numpy as np

# ======================
# Setup
# ======================
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
torch.manual_seed(0)

activations = ["relu", "tanh", "sigmoid", "gelu"]
depths = [2, 4, 6]
epochs = 20
batch_size = 128

# ======================
# Data
# ======================
transform = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize((0.5, 0.5, 0.5),
                         (0.5, 0.5, 0.5))
])

full_trainset = torchvision.datasets.CIFAR10(
    root='./data', train=True, download=True, transform=transform
)

train_size = int(0.8 * len(full_trainset))
val_size = len(full_trainset) - train_size
trainset, valset = torch.utils.data.random_split(full_trainset, [train_size, val_size])

trainloader = torch.utils.data.DataLoader(trainset, batch_size=batch_size, shuffle=True)
valloader = torch.utils.data.DataLoader(valset, batch_size=batch_size, shuffle=False)

testset = torchvision.datasets.CIFAR10(
    root='./data', train=False, download=True, transform=transform
)
testloader = torch.utils.data.DataLoader(testset, batch_size=batch_size, shuffle=False)

# ======================
# Activation
# ======================
def get_activation(name):
    return {
        "relu": nn.ReLU(),
        "tanh": nn.Tanh(),
        "sigmoid": nn.Sigmoid(),
        "gelu": nn.GELU()
    }[name]

# ======================
# CNN Model
# ======================
class CNN(nn.Module):
    def __init__(self, depth, activation):
        super().__init__()

        act = get_activation(activation)
        layers = []

        in_channels = 3
        channels = 32

        # Convolutional blocks
        for i in range(depth): # i is 0-indexed block number
            layers.append(nn.Conv2d(in_channels, channels, kernel_size=3, padding=1))

            # Calculate spatial dimension after previous pooling and current conv
            # Assuming 32x32 initial input. Each MaxPool2d halves the dimension.
            # So, after `i` MaxPool2d operations (from previous blocks), the current spatial dim is 32 / (2**i).
            current_spatial_dim = 32 // (2**i)

            # Only add BatchNorm2d if spatial dimensions are not 1x1
            if current_spatial_dim > 1:
                layers.append(nn.BatchNorm2d(channels))
            else:
                # If spatial dimension is 1x1, use nn.Identity() instead of BatchNorm2d
                layers.append(nn.Identity()) # Placeholder, effectively no-op

            layers.append(act)

            # Apply MaxPool2d only if current_spatial_dim is greater than 1
            if current_spatial_dim > 1:
                layers.append(nn.MaxPool2d(2))
            else:
                # If spatial dimension is 1x1, use nn.Identity() instead of MaxPool2d
                layers.append(nn.Identity()) # Placeholder for MaxPool2d

            in_channels = channels
            channels *= 2

        self.conv = nn.Sequential(*layers)

        # Compute flattened size dynamically
        with torch.no_grad():
            dummy = torch.zeros(1, 3, 32, 32)
            out = self.conv(dummy)
            self.flat_dim = out.view(1, -1).shape[1]

        self.fc = nn.Linear(self.flat_dim, 10)

    def forward(self, x):
        x = self.conv(x)
        x = x.view(x.size(0), -1)
        return self.fc(x)

# ======================
# Train Function
# ======================
def train(model, loader, optimizer, criterion):
    model.train()
    correct, total = 0, 0

    for x, y in loader:
        x, y = x.to(device), y.to(device)

        optimizer.zero_grad()
        out = model(x)
        loss = criterion(out, y)
        loss.backward()
        optimizer.step()

        pred = out.argmax(dim=1)
        correct += (pred == y).sum().item()
        total += y.size(0)

    return correct / total

# ======================
# Evaluation + Margins
# ======================
def evaluate(model, loader):
    model.eval()
    correct, total = 0, 0
    margins = []

    with torch.no_grad():
        for x, y in loader:
            x, y = x.to(device), y.to(device)
            out = model(x)

            pred = out.argmax(dim=1)
            correct += (pred == y).sum().item()
            total += y.size(0)

            # Vectorized margin computation
            correct_scores = out[torch.arange(len(y)), y]

            temp = out.clone()
            temp[torch.arange(len(y)), y] = -1e9
            second_best = temp.max(dim=1).values

            batch_margins = (correct_scores - second_best).cpu().numpy()
            margins.extend(batch_margins)

    return correct / total, margins

# ======================
# Experiment Loop
# ======================
results = {}

for depth in depths:
    for act in activations:
        print(f"\n=== Depth={depth}, Activation={act} ===")

        model = CNN(depth, act).to(device)
        optimizer = optim.Adam(model.parameters(), lr=0.001)
        criterion = nn.CrossEntropyLoss()

        train_hist, val_hist = [], []

        for ep in range(epochs):
            train_acc = train(model, trainloader, optimizer, criterion)
            val_acc, _ = evaluate(model, valloader)

            train_hist.append(train_acc)
            val_hist.append(val_acc)

            print(f"Epoch {ep+1}: Train={train_acc:.4f}, Val={val_acc:.4f}")

        test_acc, test_margins = evaluate(model, testloader)
        train_acc_final, train_margins = evaluate(model, trainloader)

        gap = train_acc_final - test_acc

        results[(act, depth)] = {
            "train_hist": train_hist,
            "val_hist": val_hist,
            "test_acc": test_acc,
            "gap": gap,
            "train_margins": train_margins,
            "test_margins": test_margins
        }

# ======================
# PLOTS
# ======================

# Accuracy curves
for depth in depths:
    plt.figure()
    for act in activations:
        plt.plot(results[(act, depth)]["train_hist"], '--', label=f"{act}-train")
        plt.plot(results[(act, depth)]["val_hist"], '-', label=f"{act}-val")

    plt.title(f"Accuracy | Depth={depth}")
    plt.xlabel("Epoch")
    plt.ylabel("Accuracy")
    plt.legend()
    plt.show()

# Test accuracy comparison
for depth in depths:
    plt.figure()
    accs = [results[(act, depth)]["test_acc"] for act in activations]
    plt.bar(activations, accs)

    plt.title(f"Test Accuracy | Depth={depth}")
    plt.ylabel("Accuracy")
    plt.show()

# Generalization gap
for depth in depths:
    plt.figure()
    gaps = [results[(act, depth)]["gap"] for act in activations]
    plt.bar(activations, gaps)

    plt.title(f"Generalization Gap | Depth={depth}")
    plt.ylabel("Gap")
    plt.show()

# Margin distributions (TEST)
for depth in depths:
    plt.figure()
    for act in activations:
        margins = results[(act, depth)]["test_margins"]
        plt.hist(margins, bins=50, alpha=0.4, label=act)

    plt.title(f"Test Margin Distribution | Depth={depth}")
    plt.legend()
    plt.show()

# Mean margin comparison
for depth in depths:
    plt.figure()

    means = [
        np.mean(results[(act, depth)]["test_margins"])
        for act in activations
    ]

    plt.bar(activations, means)
    plt.title(f"Mean Margin | Depth={depth}")
    plt.ylabel("Margin")
    plt.show()